---
title: "Data"
layout: article
---


This data product contains the classification of the entire building stock of 10 European countries, geographically split based on [NUTS1 regions (2024)](https://ec.europa.eu/eurostat/web/nuts/maps).



## Available data

Below is an overview of the available data.

### Coverage

The current coverage includes Austria, Belgium, Czechia, France, Germany, Lithuania, the Netherlands, Poland, Slovakia, and Spain.
Additional European countries are expected in 2026.

### Releases

The dataset is currently split in two releases. The first one, from September 2025, covers
Austria, Czechia, Germany, Lithuania, Poland, and Slovakia. The second, from November 2025
covers Belgium, France, the Netherlands, and Spain (withut Basque region). The countries
from the latter release are assgined to the existing taxonomic tree (as of now).

### Contents

Structure of all releases:

-   `{NUTS1}.parquet` / `{NUTS1}.gpkg` - Hierarchical Morphotope Classification results linked to
        building geometry (available as both Parquet and GPKG)
-   `{NUTS1}_morphotopes.parquet` / `{NUTS1}_morphotopes.gpkg` - Hierarchical Morphotope Classification results
        linked to morphotope geometry (available as both Parquet and GPKG)
-   `{NUTS1}_data.parquet` - Underlying morphometric data linkable to building geometry
-   `morphotope_data.parquet` - Aggregated data linkable to individual morphotopes

Additional files available in the initial release (2025-09):

-   `label_name.json` - Names of the cluster labels for the first three levels of taxonomy
-   `pen_portraits.json` - Descriptions of the clusters for the first three levels of
    taxonomy
-   `ward_linkage.npy` - The taxonomy itself encoded as a scipy linkage object

Additionally, the repository managed by Charles University contains PMTiles representation.

- `complete.pmtiles` - Hierarchical Morphotope Classification results linked to
    building geometry as a single PMTiles object

### File formats

The majority of the data is stored as Apache Parquet, with geospatial data being encoded
as [GeoParquet](https://geoparquet.org/) or as GPKG (GeoPackage) for direct download.

The data is split regionally based on NUTS1 regions.

-   `{NUTS1}.parquet` - GeoParquet 1.1.0, ZSTD compressed, with GeoArrow geometry encoding and covering bbox for fast spatial queries.
-   `{NUTS1}.gpkg` - GPKG (GeoPackage), direct download only.
-   `{NUTS1}_morphotopes.parquet` - GeoParquet 1.1.0, ZSTD compressed, with GeoArrow geometry encoding and covering bbox for fast spatial queries.
-   `{NUTS1}_morphotopes.gpkg` - GPKG (GeoPackage), direct download only.
-   `{NUTS1}_data.parquet` - Parquet, ZSTD compressed
-   `morphotope_data.parquet` - Parquet, Snappy compressed. All characters for
    non-outlier morphotopes - used to build the taxonomy.
-   `label_name.json` - JSON
-   `pen_portraits.json` - JSON
-   `ward_linkage.npy` - Numpy NPY
-   `complete.pmtiles` - PMTiles

## Data repositories

### Zenodo

The main data repository is Zenodo, which contains a complete copy of the data product
and issues a DOI to each version.

#### 2025-09 release

The initial release covering **AT, CZ, DE, LT, PL, SK** is avaialble from [doi.org/10.5281/zenodo.17076283](https://doi.org/10.5281/zenodo.17076283).

#### 2025-11 release

The first expansion covering **BE, NL, FR, ES** is asvailable from [doi.org/10.5281/zenodo.17600617](https://doi.org/10.5281/zenodo.17600617).

### Direct download

You can also download the data directly from the repository managed by Charles University.

#### 2025-09 release

::: {.callout-tip collapse=true appearance="minimal"}
#### Austria

| NUTS1 | HiMoC on buildings | HiMoC on morphotopes | Morphometric data |
|----|----|----|----|
| AT1 | [Parquet (165M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at1.parquet)<br>[GPKG (475M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at1.gpkg) | [Parquet (194M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at1_morphotopes.parquet)<br>[GPKG (413M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at1_morphotopes.gpkg) | [Parquet (558M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at1_data.parquet) |
| AT2 | [Parquet (113M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at2.parquet)<br>[GPKG (334M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at2.gpkg) | [Parquet (148M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at2_morphotopes.parquet)<br>[GPKG (328M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at2_morphotopes.gpkg) | [Parquet (411M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at2_data.parquet) |
| AT3 | [Parquet (156M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at3.parquet)<br>[GPKG (448M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at3.gpkg) | [Parquet (199M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at3_morphotopes.parquet)<br>[GPKG (439M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at3_morphotopes.gpkg) | [Parquet (639M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/at3_data.parquet) |

:::
::: {.callout-tip collapse=true appearance="minimal"}
#### Czechia

| NUTS1 | HiMoC on buildings | HiMoC on morphotopes | Morphometric data |
|----|----|----|----|
| CZ0 | [Parquet (423M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/cz0.parquet)<br>[GPKG (1.3G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/cz0.gpkg) | [Parquet (435M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/cz0_morphotopes.parquet)<br>[GPKG (930M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/cz0_morphotopes.gpkg) | [Parquet (1.7G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/cz0_data.parquet) |

:::
::: {.callout-tip collapse=true appearance="minimal"}
#### Germany

| NUTS1 | HiMoC on buildings | HiMoC on morphotopes | Morphometric data |
|----|----|----|----|
| DE1 | [Parquet (554M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de1.parquet)<br>[GPKG (1.7G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de1.gpkg) | [Parquet (612M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de1_morphotopes.parquet)<br>[GPKG (1.3G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de1_morphotopes.gpkg) | [Parquet (1.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de1_data.parquet) |
| DE2 | [Parquet (824M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de2.parquet)<br>[GPKG (2.6G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de2.gpkg) | [Parquet (930M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de2_morphotopes.parquet)<br>[GPKG (2.0G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de2_morphotopes.gpkg) | [Parquet (2.0G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de2_data.parquet) |
| DE3 | [Parquet (63M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de3.parquet)<br>[GPKG (176M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de3.gpkg) | [Parquet (67M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de3_morphotopes.parquet)<br>[GPKG (134M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de3_morphotopes.gpkg) | [Parquet (192M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de3_data.parquet) |
| DE4 | [Parquet (194M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de4.parquet)<br>[GPKG (614M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de4.gpkg) | [Parquet (226M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de4_morphotopes.parquet)<br>[GPKG (474M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de4_morphotopes.gpkg) | [Parquet (647M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de4_data.parquet) |
| DE5 | [Parquet (25M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de5.parquet)<br>[GPKG (68M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de5.gpkg) | [Parquet (24M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de5_morphotopes.parquet)<br>[GPKG (48M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de5_morphotopes.gpkg) | [Parquet (215M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de5_data.parquet) |
| DE6 | [Parquet (42M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de6.parquet)<br>[GPKG (116M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de6.gpkg) | [Parquet (49M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de6_morphotopes.parquet)<br>[GPKG (97M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de6_morphotopes.gpkg) | [Parquet (209M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de6_data.parquet) |
| DE7 | [Parquet (358M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de7.parquet)<br>[GPKG (1.1G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de7.gpkg) | [Parquet (370M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de7_morphotopes.parquet)<br>[GPKG (774M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de7_morphotopes.gpkg) | [Parquet (3.1G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de7_data.parquet) |
| DE8 | [Parquet (116M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de8.parquet)<br>[GPKG (363M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de8.gpkg) | [Parquet (122M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de8_morphotopes.parquet)<br>[GPKG (260M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de8_morphotopes.gpkg) | [Parquet (364M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de8_data.parquet) |
| DE9 | [Parquet (549M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de9.parquet)<br>[GPKG (1.7G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de9.gpkg) | [Parquet (612M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de9_morphotopes.parquet)<br>[GPKG (1.3G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de9_morphotopes.gpkg) | [Parquet (3.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/de9_data.parquet) |
| DEA | [Parquet (905M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dea.parquet)<br>[GPKG (2.7G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dea.gpkg) | [Parquet (985M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dea_morphotopes.parquet)<br>[GPKG (2.0G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dea_morphotopes.gpkg) | [Parquet (2.5G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dea_data.parquet) |
| DEB | [Parquet (261M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/deb.parquet)<br>[GPKG (793M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/deb.gpkg) | [Parquet (264M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/deb_morphotopes.parquet)<br>[GPKG (547M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/deb_morphotopes.gpkg) | [Parquet (3.0G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/deb_data.parquet) |
| DEC | [Parquet (53M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dec.parquet)<br>[GPKG (154M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dec.gpkg) | [Parquet (59M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dec_morphotopes.parquet)<br>[GPKG (119M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dec_morphotopes.gpkg) | [Parquet (126M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dec_data.parquet) |
| DED | [Parquet (191M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/ded.parquet)<br>[GPKG (582M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/ded.gpkg) | [Parquet (221M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/ded_morphotopes.parquet)<br>[GPKG (460M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/ded_morphotopes.gpkg) | [Parquet (544M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/ded_data.parquet) |
| DEE | [Parquet (162M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dee.parquet)<br>[GPKG (473M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dee.gpkg) | [Parquet (177M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dee_morphotopes.parquet)<br>[GPKG (368M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dee_morphotopes.gpkg) | [Parquet (486M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/dee_data.parquet) |
| DEF | [Parquet (198M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/def.parquet)<br>[GPKG (607M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/def.gpkg) | [Parquet (215M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/def_morphotopes.parquet)<br>[GPKG (453M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/def_morphotopes.gpkg) | [Parquet (466M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/def_data.parquet) |
| DEG | [Parquet (165M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/deg.parquet)<br>[GPKG (533M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/deg.gpkg) | [Parquet (183M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/deg_morphotopes.parquet)<br>[GPKG (383M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/deg_morphotopes.gpkg) | [Parquet (571M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/deg_data.parquet) |

:::
::: {.callout-tip collapse=true appearance="minimal"}
#### Lithuania

| NUTS1 | HiMoC on buildings | HiMoC on morphotopes | Morphometric data |
|----|----|----|----|
| LT0 | [Parquet (188M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/lt0.parquet)<br>[GPKG (568M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/lt0.gpkg) | [Parquet (255M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/lt0_morphotopes.parquet)<br>[GPKG (580M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/lt0_morphotopes.gpkg) | [Parquet (332M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/lt0_data.parquet) |

:::
::: {.callout-tip collapse=true appearance="minimal"}
#### Poland

| NUTS1 | HiMoC on buildings | HiMoC on morphotopes | Morphometric data |
|----|----|----|----|
| PL2 | [Parquet (245M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl2.parquet)<br>[GPKG (758M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl2.gpkg) | [Parquet (315M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl2_morphotopes.parquet)<br>[GPKG (655M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl2_morphotopes.gpkg) | [Parquet (711M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl2_data.parquet) |
| PL4 | [Parquet (210M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl4.parquet)<br>[GPKG (648M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl4.gpkg) | [Parquet (249M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl4_morphotopes.parquet)<br>[GPKG (541M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl4_morphotopes.gpkg) | [Parquet (788M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl4_data.parquet) |
| PL5 | [Parquet (113M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl5.parquet)<br>[GPKG (344M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl5.gpkg) | [Parquet (130M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl5_morphotopes.parquet)<br>[GPKG (274M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl5_morphotopes.gpkg) | [Parquet (938M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl5_data.parquet) |
| PL6 | [Parquet (173M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl6.parquet)<br>[GPKG (532M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl6.gpkg) | [Parquet (222M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl6_morphotopes.parquet)<br>[GPKG (503M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl6_morphotopes.gpkg) | [Parquet (487M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl6_data.parquet) |
| PL7 | [Parquet (160M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl7.parquet)<br>[GPKG (511M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl7.gpkg) | [Parquet (199M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl7_morphotopes.parquet)<br>[GPKG (427M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl7_morphotopes.gpkg) | [Parquet (1.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl7_data.parquet) |
| PL8 | [Parquet (251M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl8.parquet)<br>[GPKG (804M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl8.gpkg) | [Parquet (321M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl8_morphotopes.parquet)<br>[GPKG (696M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl8_morphotopes.gpkg) | [Parquet (1.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl8_data.parquet) |
| PL9 | [Parquet (198M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl9.parquet)<br>[GPKG (612M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl9.gpkg) | [Parquet (248M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl9_morphotopes.parquet)<br>[GPKG (534M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl9_morphotopes.gpkg) | [Parquet (636M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pl9_data.parquet) |

:::
::: {.callout-tip collapse=true appearance="minimal"}
#### Slovakia

| NUTS1 | HiMoC on buildings | HiMoC on morphotopes | Morphometric data |
|----|----|----|----|
| SK0 | [Parquet (275M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/sk0.parquet)<br>[GPKG (893M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/sk0.gpkg) | [Parquet (361M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/sk0_morphotopes.parquet)<br>[GPKG (759M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/sk0_morphotopes.gpkg) | [Parquet (1.1G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/sk0_data.parquet) |
:::

::: {.callout-tip collapse=true appearance="minimal"}
#### Common files

| File name | Download |
|----|----|
| Morphotope data | [Parquet (200M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/morphotope_data.parquet) |
| Label to name mapping | [JSON (4K)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/label_name.json) |
| Descriptions of named branches | [JSON (8K)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/pen_portraits.json) |
| Taxonomy linkage | [NPY (16M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/ward_linkage.npy) |
| Complete classification as PMtiles | [PMTiles (7.8G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202509/complete.pmtiles) |
:::


#### 2025-11 release

::: {.callout-tip collapse=true appearance="minimal"}
#### Belgium

| NUTS1 | HiMoC on buildings | HiMoC on morphotopes | Morphometric data |
|----|----|----|----|
| BE1 | [Parquet (23M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be1.parquet)<br>[GPKG (70M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be1.gpkg) | [Parquet (15M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be1_morphotopes.parquet)<br>[GPKG (30M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be1_morphotopes.gpkg) | [Parquet (850M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be1_data.parquet) |
| BE2 | [Parquet (402M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be2.parquet)<br>[GPKG (1.7G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be2.gpkg) | [Parquet (404M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be2_morphotopes.parquet)<br>[GPKG (834M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be2_morphotopes.gpkg) | [Parquet (1.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be2_data.parquet) |
| BE3 | [Parquet (191M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be3.parquet)<br>[GPKG (828M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be3.gpkg) | [Parquet (183M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be3_morphotopes.parquet)<br>[GPKG (386M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be3_morphotopes.gpkg) | [Parquet (1.4G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/be3_data.parquet) |

:::

::: {.callout-tip collapse=true appearance="minimal"}
#### France

| NUTS1 | HiMoC on buildings | HiMoC on morphotopes | Morphometric data |
|----|----|----|----|
| FR1 | [Parquet (299M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fr1.parquet)<br>[GPKG (1.1G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fr1.gpkg) | [Parquet (266M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fr1_morphotopes.parquet)<br>[GPKG (548M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fr1_morphotopes.gpkg) | [Parquet (591M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fr1_data.parquet) |
| FRB | [Parquet (219M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frb.parquet)<br>[GPKG (828M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frb.gpkg) | [Parquet (218M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frb_morphotopes.parquet)<br>[GPKG (487M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frb_morphotopes.gpkg) | [Parquet (997M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frb_data.parquet) |
| FRC | [Parquet (231M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frc.parquet)<br>[GPKG (868M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frc.gpkg) | [Parquet (224M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frc_morphotopes.parquet)<br>[GPKG (496M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frc_morphotopes.gpkg) | [Parquet (660M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frc_data.parquet) |
| FRD | [Parquet (252M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frd.parquet)<br>[GPKG (969M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frd.gpkg) | [Parquet (249M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frd_morphotopes.parquet)<br>[GPKG (547M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frd_morphotopes.gpkg) | [Parquet (975M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frd_data.parquet) |
| FRE | [Parquet (392M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fre.parquet)<br>[GPKG (1.5G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fre.gpkg) | [Parquet (335M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fre_morphotopes.parquet)<br>[GPKG (710M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fre_morphotopes.gpkg) | [Parquet (1.9G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fre_data.parquet) |
| FRF | [Parquet (371M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frf.parquet)<br>[GPKG (1.4G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frf.gpkg) | [Parquet (336M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frf_morphotopes.parquet)<br>[GPKG (720M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frf_morphotopes.gpkg) | [Parquet (1.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frf_data.parquet) |
| FRG | [Parquet (326M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frg.parquet)<br>[GPKG (1.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frg.gpkg) | [Parquet (312M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frg_morphotopes.parquet)<br>[GPKG (692M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frg_morphotopes.gpkg) | [Parquet (853M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frg_data.parquet) |
| FRH | [Parquet (286M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frh.parquet)<br>[GPKG (1.1G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frh.gpkg) | [Parquet (274M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frh_morphotopes.parquet)<br>[GPKG (604M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frh_morphotopes.gpkg) | [Parquet (595M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frh_data.parquet) |
| FRI | [Parquet (587M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fri.parquet)<br>[GPKG (2.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fri.gpkg) | [Parquet (582M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fri_morphotopes.parquet)<br>[GPKG (1.3G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fri_morphotopes.gpkg) | [Parquet (1.3G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/fri_data.parquet) |
| FRJ | [Parquet (503M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frj.parquet)<br>[GPKG (1.9G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frj.gpkg) | [Parquet (507M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frj_morphotopes.parquet)<br>[GPKG (1.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frj_morphotopes.gpkg) | [Parquet (1.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frj_data.parquet) |
| FRK | [Parquet (507M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frk.parquet)<br>[GPKG (1.9G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frk.gpkg) | [Parquet (510M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frk_morphotopes.parquet)<br>[GPKG (1.1G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frk_morphotopes.gpkg) | [Parquet (1.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frk_data.parquet) |
| FRL | [Parquet (300M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frl.parquet)<br>[GPKG (1.1G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frl.gpkg) | [Parquet (298M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frl_morphotopes.parquet)<br>[GPKG (630M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frl_morphotopes.gpkg) | [Parquet (600M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frl_data.parquet) |
| FRM | [Parquet (29M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frm.parquet)<br>[GPKG (102M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frm.gpkg) | [Parquet (31M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frm_morphotopes.parquet)<br>[GPKG (69M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frm_morphotopes.gpkg) | [Parquet (58M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/frm_data.parquet) |

:::

::: {.callout-tip collapse=true appearance="minimal"}
#### The Netherlands

| NUTS1 | HiMoC on buildings | HiMoC on morphotopes | Morphometric data |
|----|----|----|----|
| NL1 | [Parquet (121M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl1.parquet)<br>[GPKG (456M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl1.gpkg) | [Parquet (116M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl1_morphotopes.parquet)<br>[GPKG (248M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl1_morphotopes.gpkg) | [Parquet (480M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl1_data.parquet) |
| NL2 | [Parquet (225M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl2.parquet)<br>[GPKG (880M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl2.gpkg) | [Parquet (218M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl2_morphotopes.parquet)<br>[GPKG (459M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl2_morphotopes.gpkg) | [Parquet (3.1G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl2_data.parquet) |
| NL3 | [Parquet (370M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl3.parquet)<br>[GPKG (1.5G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl3.gpkg) | [Parquet (341M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl3_morphotopes.parquet)<br>[GPKG (709M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl3_morphotopes.gpkg) | [Parquet (1.7G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl3_data.parquet) |
| NL4 | [Parquet (240M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl4.parquet)<br>[GPKG (932M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl4.gpkg) | [Parquet (226M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl4_morphotopes.parquet)<br>[GPKG (468M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl4_morphotopes.gpkg) | [Parquet (3.6G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/nl4_data.parquet) |

:::

::: {.callout-tip collapse=true appearance="minimal"}
#### Spain

Spain currently does not contain Basque region.

| NUTS1 | HiMoC on buildings | HiMoC on morphotopes | Morphometric data |
|----|----|----|----|
| ES1 | [Parquet (212M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es1.parquet)<br>[GPKG (628M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es1.gpkg) | [Parquet (219M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es1_morphotopes.parquet)<br>[GPKG (482M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es1_morphotopes.gpkg) | [Parquet (456M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es1_data.parquet) |
| ES2 | [Parquet (73M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es2.parquet)<br>[GPKG (303M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es2.gpkg) | [Parquet (82M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es2_morphotopes.parquet)<br>[GPKG (192M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es2_morphotopes.gpkg) | [Parquet (471M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es2_data.parquet) |
| ES3 | [Parquet (93M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es3.parquet)<br>[GPKG (255M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es3.gpkg) | [Parquet (64M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es3_morphotopes.parquet)<br>[GPKG (134M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es3_morphotopes.gpkg) | [Parquet (295M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es3_data.parquet) |
| ES4 | [Parquet (390M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es4.parquet)<br>[GPKG (1.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es4.gpkg) | [Parquet (382M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es4_morphotopes.parquet)<br>[GPKG (881M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es4_morphotopes.gpkg) | [Parquet (1.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es4_data.parquet) |
| ES5 | [Parquet (406M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es5.parquet)<br>[GPKG (1.6G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es5.gpkg) | [Parquet (358M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es5_morphotopes.parquet)<br>[GPKG (783M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es5_morphotopes.gpkg) | [Parquet (807M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es5_data.parquet) |
| ES6 | [Parquet (391M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es6.parquet)<br>[GPKG (1.2G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es6.gpkg) | [Parquet (337M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es6_morphotopes.parquet)<br>[GPKG (757M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es6_morphotopes.gpkg) | [Parquet (748M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es6_data.parquet) |
| ES7 | [Parquet (73M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es7.parquet)<br>[GPKG (194M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es7.gpkg) | [Parquet (59M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es7_morphotopes.parquet)<br>[GPKG (120M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es7_morphotopes.gpkg) | [Parquet (105M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/es7_data.parquet) |
:::

::: {.callout-tip collapse=true appearance="minimal"}
#### Common files

| File name | Download |
|----|----|
| Morphotope data | [Parquet (184M)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/morphotope_data.parquet) |
| Complete classification as PMtiles | [PMTiles (16G)](https://s3.cl4.du.cesnet.cz/4f4743b6_4043_4e02_a3ba_0452aa7523a2:uscuni-public/urban_taxonomy/v202511/complete.pmtiles) |
:::

## License

This dataset is based on data from multiple sources. The combined database is licensed
under the Open Database License (ODbL) v1.0.

**Attribution:** Contains data © Charles University, OpenStreetMap contributors, TomTom,
GeoBasis-DE/LGB, GeoSN, LGL Baden-Württemberg, GeoBasis-DE/MV, GeoBasis-DE/LVGL-SL,
IT.NRW, GeoBasis-DE/LGLN, GDI-Th, LVermGeo ST, GeoBasis-DE/LVermGeo SH, Bayerische
Vermessungsverwaltung, LGV Hamburg, Landesamt GeoInformation Bremen, GUGiK (PL), ČÚZK
(CZ), ÚGKK SR (SK), BEV (AT), Geoportal.lt (LT), IGN, 3DGI, DGC, and others.

Individual source building data is available under the following licenses and
attributions:

-   **Brandenburg**: GeoBasis-DE/LGB — [Datenlizenz Deutschland – Namensnennung –
    Version 2.0](https://www.govdata.de/dl-de/by-2-0)
-   **Saxony**: State Office for Geobasis Information Saxony (GeoSN) — [Datenlizenz
    Deutschland – Namensnennung – Version 2.0](https://www.govdata.de/dl-de/by-2-0)
-   **Baden-Württemberg**: LGL, [www.lgl-bw.de](http://www.lgl-bw.de/) — [Datenlizenz
    Deutschland – Namensnennung – Version 2.0](https://www.govdata.de/dl-de/by-2-0)
-   **Mecklenburg-Vorpommern**: GeoBasis-DE/MV — CC-BY 4.0
-   **Rheinland-Pfalz**: GeoBasis-DE/LGB — [Datenlizenz Deutschland – Namensnennung –
    Version 2.0](https://www.govdata.de/dl-de/by-2-0)
-   **Saarland**: © GeoBasis-DE/LVGL-SL (2024) — [Datenlizenz Deutschland –
    Namensnennung – Version 2.0](https://www.govdata.de/dl-de/by-2-0)
-   **Nordrhein-Westfalen**: Geoinformationszentrum, Information und Technik
    Nordrhein-Westfalen — [Datenlizenz Deutschland – Namensnennung – Version
    2.0](https://www.govdata.de/dl-de/by-2-0)
-   **Niedersachsen**: © GeoBasis-DE/LGLN — CC-BY 4.0
-   **Hessen**: Datenlizenz Deutschland – Zero – Version 2.0
-   **Thuringia**: © GDI-Th — [Datenlizenz Deutschland – Namensnennung – Version
    2.0](https://www.govdata.de/dl-de/by-2-0)
-   **Saxony-Anhalt**: GeoBasis-DE / LVermGeo ST — [Datenlizenz Deutschland –
    Namensnennung – Version 2.0](https://www.govdata.de/dl-de/by-2-0)
-   **Schleswig-Holstein**: © GeoBasis-DE/LVermGeo SH — CC-BY-SA 4.0
-   **Bavaria**: Bayerische Vermessungsverwaltung — CC-BY 4.0
-   **Berlin**: Datenlizenz Deutschland – Zero – Version 2.0
-   **Hamburg**: © LGV Hamburg — [Datenlizenz Deutschland – Namensnennung – Version
    2.0](https://www.govdata.de/dl-de/by-2-0)
-   **Bremen**: Landesamt GeoInformation Bremen — CC-BY 4.0
-   **Poland**: Główny Urząd Geodezji i Kartografii — CC-BY 4.0
-   **Czechia**: ČÚZK — CC-BY 4.0
-   **Slovakia**: Úrad geodézie, kartografie a katastra SR — CC-BY 4.0
-   **Austria**: BEV — CC-BY 4.0
-   **Lithuania**: Geoportal.lt — CC-BY 4.0
-   **France**: Licence Ouverte / Open Licence 2.0 © IGN
-   **Belgium**: Open Database License (ODbL) OpenStreetMap Contributors
-   **Netherlands**: CC-BY-4.0 © 3DBAG by tudelft3d and 3DGI
-   **Spain**: LICENCIA DE ACCESO Y USO DE LOS SERVICIOS Y CONJUNTOS DE DATOS INSPIRE DE LA DIRECCIÓN GENERAL DEL CATASTRO © DGC